### Question1:
Create a 3x3x3 array with random values

In [29]:
import numpy as np

arr = np.random.random((3,3,3))
arr

array([[[0.42745106, 0.18152468, 0.91710348],
        [0.1045465 , 0.69777794, 0.41684034],
        [0.3898652 , 0.9935426 , 0.8667405 ]],

       [[0.71645102, 0.4170301 , 0.1940561 ],
        [0.15213657, 0.18370878, 0.25147186],
        [0.7750262 , 0.23675132, 0.14682477]],

       [[0.64044739, 0.56547238, 0.33839671],
        [0.31322966, 0.57776883, 0.18558277],
        [0.91295092, 0.96775161, 0.30416991]]])

### Question 2.
Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [30]:
arr1 = np.diag(1+np.arange(4),k=-1)
print(arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Question 3:
Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
arr2 = np.zeros((8,8),dtype=int)
arr2[1::2,::2] = 1
arr2[::2,1::2] = 1
print(arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Question 4: 
Normalize a 5x5 random matrix

In [32]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.64858654 -1.29195661  0.39301626  0.72435722  0.40674318]
 [-0.61509259  2.09230731 -0.53401968  1.47673982  1.57036245]
 [-1.04561396 -1.2086716  -0.61849331  0.13103381 -0.29068516]
 [-1.64393575  0.59449461 -1.72596328  0.63317862  0.37907563]
 [-0.26319228 -0.41992614  0.37171483  1.20148318 -0.96554308]]


### Question 5:
How to find common values between two arrays?

In [33]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 3 7]


### Question 6:
How to get the dates of yesterday, today and tomorrow?

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-29
2020-07-30
2020-07-31


### Question 7:
Consider two random array A and B, check if they are equal

In [35]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Check both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


### Question 8:
Create random vector of size 10 and replace the maximum value by 0

In [36]:
arr3 = np.random.random(10)
arr3[arr3.argmax()] = 0
print(arr3)

[0.62626447 0.51967611 0.         0.37339031 0.38990953 0.03519361
 0.44633714 0.63193112 0.08036265 0.62606277]


### Question 9:
How to print all the values of an array?

In [39]:
np.set_printoptions(threshold = float("inf"))
arr4 = np.zeros((16,16))
print(arr4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Question 10:
Subtract the mean of each row of a matrix

In [40]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.29402357  0.16053798 -0.09850058  0.24104278 -0.17069219 -0.15625434
  -0.15991126  0.17885543 -0.52058944  0.23148805]
 [-0.145002    0.20410673 -0.30460454 -0.12998786  0.34406424 -0.24836378
  -0.27915007  0.56372933  0.04154391 -0.04633596]
 [ 0.0783096  -0.12848065 -0.53315191 -0.08069078  0.26608904  0.24291122
   0.14026154  0.14722048 -0.14704469  0.01457616]
 [ 0.37166781  0.34311098 -0.4599966  -0.28186499 -0.12121562  0.38072372
  -0.14063753 -0.54087708  0.39099512  0.05809419]
 [-0.04002779 -0.37625639  0.4458012  -0.2877721   0.24115502  0.46214786
   0.15329527 -0.31985447 -0.14246837 -0.13602024]]
[[ 0.29402357  0.16053798 -0.09850058  0.24104278 -0.17069219 -0.15625434
  -0.15991126  0.17885543 -0.52058944  0.23148805]
 [-0.145002    0.20410673 -0.30460454 -0.12998786  0.34406424 -0.24836378
  -0.27915007  0.56372933  0.04154391 -0.04633596]
 [ 0.0783096  -0.12848065 -0.53315191 -0.08069078  0.26608904  0.24291122
   0.14026154  0.14722048 -0.14704469  0.01457616]

### Question 11:
Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [41]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 2. 4. 3. 2. 1. 5. 3. 3.]


In [42]:
np.add.at(Z, I, 1)
print(Z)

[7. 5. 3. 7. 5. 3. 1. 9. 5. 5.]


### Question 12:
How to get the diagonal of a dot product?

In [43]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.44396557 0.13340572 0.1667214  0.63978281 0.43948938]
 [0.82108654 0.16199383 0.42351048 0.64295544 0.50908061]
 [0.13786763 0.37147007 0.13680449 0.87708783 0.19382825]
 [0.02480843 0.96990068 0.93646821 0.24715994 0.89017547]
 [0.4817506  0.84308117 0.01167663 0.69009124 0.16502067]]
[[0.41249008 0.75538797 0.9704824  0.60284431 0.46527262]
 [0.32198645 0.89620332 0.82733383 0.80083663 0.64249209]
 [0.65856141 0.6542424  0.02437217 0.27187609 0.1623304 ]
 [0.6947582  0.31523815 0.87607678 0.72869289 0.1562463 ]
 [0.90142453 0.57919869 0.26051373 0.64330587 0.09777009]]
diagonal of a dot product method 1 is.... [1.17654336 1.54003972 1.26335329 1.79904972 0.89167211]
diagonal of a dot product method 2 is.... [1.17654336 1.54003972 1.26335329 1.79904972 0.89167211]


### Question 13:
How to find the most frequent value in an array?

In [44]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[7 5 4 4 9 8 3 7 8 6 6 1 4 0 5 6 1 6 9 3 9 1 3 5 6 5 3 6 5 7 1 8 8 6 7 0 1
 9 7 2 6 7 0 6 2 0 7 0 0 0]
6


### Question 14:
How to get the n largest values of an array

In [45]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


### Question 15:
How to create a record array from a regular array?

In [46]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Z2 = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Z2)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
